package su.vi.simplydiapp.for_test


internal interface TestInterface123
internal interface TestInterface321
internal interface TestInterface111
internal interface TestInterface333
internal interface TestInterface222